spring.application.name=marketplace
# banco
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=marketplacedb;encrypt=true;trustServerCertificate=true;
spring.datasource.username=dbadmin
spring.datasource.password=Senha@123

# jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# porta
server.port=8080